Repository przemek06/iot_mobile, pull requests merged in 2023-11, with the labels that each got.

#22 Frontend/local database
  frontend/app/build.gradle
  frontend/app/src/main/AndroidManifest.xml
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/app/koin/AppKoin.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/app/retrofit/AppRetrofit.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/data/User.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/model/datasource/local/UserLocalDataSource.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/model/datasource/local/UserSessionLocalDataSource.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/model/datasource/local/impl/UserLocalDataSourceImpl.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/model/datasource/local/impl/UserSessionLocalDataSourceImpl.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/model/repository/UserRepository.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/model/repository/impl/UserRepositoryImpl.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/navigation/BottomNavigationBar.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/navigation/NavigationGraph.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/app/MainActivity.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/app/MainUiState.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/app/MainViewModel.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/projectdetails/ProjectDetailsViewModel.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/search/SearchViewModel.kt
  frontend/app/src/main/proto/user.proto
Labels: enhancement

#23 Frontend/add component wrapper
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/app/koin/AppKoin.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/components/ButtonCommon.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/navigation/BottomNavigationBar.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/navigation/NavigationGraph.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/addcomponent/AddComponentInteraction.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/addcomponent/AddComponentScreen.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/addcomponent/AddComponentUiState.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/addcomponent/AddComponentViewModel.kt
  frontend/app/src/main/res/values/strings.xml
Labels: enhancement

#25 Backend/fixes
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/config/SpringConfig.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/controller/ProjectController.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/controller/TopicController.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/controller/UserController.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/dto/ProjectDeletedDTO.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/dto/TopicDTO.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/entities/Component.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/entities/InputComponent.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/entities/OutputComponent.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/entities/TriggerComponent.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/error/ErrorHandler.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/error/exception/TopicUsedException.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/listener/ComponentRequestListener.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/listener/InvitationRequestListener.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/listener/OutputComponentEntityListener.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/listener/ProjectDeletedListener.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/listener/TriggerComponentEntityListener.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/repositories/InvitationRepository.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/repositories/ProjectRepository.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/repositories/TopicRepository.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/ComponentService.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/ProjectDeletedNotificationService.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/ProjectService.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/TopicService.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/UserService.kt
  docker-compose.yaml
Labels: bug, enhancement

#27 Frontend/add component api integration
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/app/koin/AppKoin.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/data/dto/ComponentDto.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/data/dto/ComponentListDto.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/data/scopestates/ComponentsListState.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/model/datasource/remote/ComponentRemoteDataSource.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/model/datasource/remote/impl/ComponentRemoteDataSourceImpl.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/model/repository/ComponentRepository.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/model/repository/impl/ComponentRepositoryImpl.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/addcomponent/AddComponentNavigation.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/addcomponent/AddComponentScreen.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/addcomponent/AddComponentUiInteraction.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/addcomponent/AddComponentViewModel.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/DashboardComponentsList.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/DashboardNavigation.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/DashboardScreen.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/DashboardUiInteraction.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/DashboardViewModel.kt
Labels: enhancement

#28 Frontend/input components
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/data/ComponentDetailedType.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/data/ComponentType.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/data/dto/ComponentDto.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/data/ui/Topic.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/components/ButtonCommon.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/addcomponent/AddComponentUiState.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/addcomponent/AddComponentViewModel.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/DashboardComponentsList.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/DashboardScreen.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/DashboardUiInteraction.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/DashboardUiState.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/DashboardViewModel.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/components/ButtonComponent.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/components/SliderComponent.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/components/ToggleComponent.kt
Labels: enhancement

#29 Backend/gmail integration
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/controller/IntegrationController.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/dto/MailMessageDTO.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/error/ErrorHandler.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/security/SecurityConfig.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/IntegrationService.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/MailService.kt
Labels: enhancement

#30 message endpoints
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/controller/MessageController.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/dto/ComponentDTO.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/dto/MessageDTO.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/dto/TopicMessagesDTO.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/entities/Component.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/entities/InputComponent.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/entities/Message.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/entities/OutputComponent.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/entities/TriggerComponent.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/listener/ComponentRequestListener.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/listener/ProjectDeletedListener.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/rabbit/RabbitListener.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/rabbit/message/MessageController.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/rabbit/message/MessageService.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/repositories/MessageRepository.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/MessageService.kt
Labels: enhancement

#35 Backend/websockets
  backend/iot_mobile/pom.xml
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/config/WebSocketConfig.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/listener/InvitationRequestListener.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/listener/ProjectDeletedListener.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/rabbit/RabbitListener.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/ComponentChangeService.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/InvitationAlertService.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/ProjectDeletedNotificationService.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/UserService.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/websocket/ComponentChangeWebSocketHandler.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/websocket/InvitationAlertWebSocketHandler.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/websocket/ProjectDeletedWebSocketHandler.kt
  frontend/app/build.gradle
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/app/koin/AppKoin.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/app/retrofit/AppRetrofit.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/app/rsocket/WebSocketClient.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/data/dto/ComponentDto.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/data/dto/InvitationAlertDto.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/data/dto/ProjectDeletedDto.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/data/ui/Topic.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/model/datasource/remote/ProjectRemoteDataSource.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/model/listener/ComponentChangeWebSocketListener.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/model/listener/InvitationAlertWebSocketListener.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/model/listener/ProjectDeletedWebSocketListener.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/model/repository/ProjectRepository.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/model/repository/impl/ProjectRepositoryImpl.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/components/InfoDialog.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/navigation/BottomNavigationBar.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/addcomponent/AddComponentViewModel.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/app/MainActivity.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/app/MainViewModel.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/DashboardScreen.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/DashboardUiState.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/DashboardViewModel.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/components/ButtonComponent.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/components/SliderComponent.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/components/ToggleComponent.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/projectdetails/ProjectDetailsScreen.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/projectdetails/ProjectDetailsUiInteraction.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/projectdetails/ProjectDetailsViewModel.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/projectdetails/TopicsScreenContent.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/projects/ProjectsViewModel.kt
  frontend/app/src/main/res/drawable/ic_copy.xml
  frontend/app/src/main/res/values/strings.xml
  frontend/gradle.properties
Labels: bug, enhancement

#33 Backend/discord
  backend/iot_mobile/pom.xml
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/controller/IntegrationController.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/dto/DiscordChannelDTO.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/dto/DiscordUrlDTO.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/entities/DiscordIntermediate.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/error/ErrorHandler.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/error/exception/DiscordNotFoundException.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/integration/DiscordBot.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/repositories/DiscordIntermediateRepository.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/IntegrationService.kt
  backend/iot_mobile/src/main/resources/application-dev.properties
Labels: enhancement

#38 Front/fix components
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/dto/ComponentDTO.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/data/ui/Topic.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/navigation/BottomNavigationBar.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/DashboardComponentsList.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/DashboardUiState.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/DashboardViewModel.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/components/SliderComponent.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/dashboard/components/ToggleComponent.kt
Labels: bug

#40 Backend/topic fix
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/TopicService.kt
Labels: bug

#41 Backend/component synch fix
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/ComponentService.kt
Labels: bug

#42 change session timeout
  backend/iot_mobile/src/main/resources/application-dev.properties
Labels: bug

#43 connecting web integrations, fixing messages
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/controller/IntegrationController.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/controller/MessageController.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/dto/ComponentDTO.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/dto/MessageDTO.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/entities/TriggerComponent.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/error/ErrorHandler.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/error/exception/TopicNotFoundException.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/integration/DiscordIntegrationAction.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/integration/EmailIntegrationAction.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/integration/IntegrationAction.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/integration/IntegrationManager.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/rabbit/RabbitListener.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/IncomingMessageService.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/IntegrationService.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/MailService.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/MessageService.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/TopicService.kt
Labels: bug, enhancement

#45 Frontend/triggers
  frontend/app/build.gradle
  frontend/app/src/main/AndroidManifest.xml
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/data/ComponentDetailedType.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/components/CheckboxWithTitle.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/addcomponent/AddComponentNavigation.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/addcomponent/AddComponentScreen.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/addcomponent/AddComponentUiInteraction.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/addcomponent/AddComponentUiState.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/addcomponent/AddComponentViewModel.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/addcomponent/AdditionalScreenContent.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/addcomponent/ChooseComponentScreenContent.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/app/MainActivity.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/app/MainViewModel.kt
  frontend/app/src/main/res/drawable/ic_discord.xml
  frontend/app/src/main/res/values/strings.xml
  frontend/gradle.properties
Labels: enhancement

#48 Backend/discord trigger
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/controller/IntegrationController.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/dto/KeyDTO.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/entities/DiscordIntermediate.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/repositories/DiscordIntermediateRepository.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/IntegrationService.kt
  backend/iot_mobile/src/main/resources/application-dev.properties
  frontend/app/src/main/AndroidManifest.xml
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/app/koin/AppKoin.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/data/dto/DiscordChannelDto.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/data/dto/UriDto.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/model/datasource/remote/IntegrationRemoteDataSource.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/model/datasource/remote/impl/IntegrationRemoteDataSourceImpl.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/model/repository/IntegrationRepository.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/model/repository/impl/IntegrationRepositoryImpl.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/components/DescriptionInputField.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/components/InputField.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/addcomponent/AddComponentScreen.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/addcomponent/AddComponentUiState.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/addcomponent/AddComponentViewModel.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/addcomponent/AdditionalScreenContent.kt
  frontend/app/src/main/java/edu/pwr/iotmobile/androidimcs/ui/screens/addcomponent/SettingsScreenContent.kt
  frontend/app/src/main/res/values/strings.xml
  frontend/gradle.properties
Labels: enhancement

#53 Backend/iot listen websocket
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/config/WebSocketConfig.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/controller/MessageController.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/controller/TopicController.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/dto/MessageDTO.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/dto/TopicConnectionDTO.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/enums/EValueType.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/integration/IntegrationManager.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/listener/ComponentRequestListener.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/rabbit/RabbitListener.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/rabbit/queue/QueueService.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/repositories/TopicRepository.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/ComponentService.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/MessageService.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/service/TopicService.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/websocket/DeviceIncomingMessageWebSocketHandler.kt
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/websocket/IncomingMessageWebSocketHandler.kt
  backend/iot_mobile/src/main/resources/application-dev.properties
  docker-compose.yaml
  frontend/gradle.properties
Labels: enhancement

#59 authorization fix
  backend/iot_mobile/src/main/kotlin/edu/pwr/iotmobile/security/SecurityConfig.kt
Labels: bug
